# Generated by Django 5.2.6 on 2025-10-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='snippet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='affiliation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='profile_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='snippet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
