# Generated by Django 5.2.6 on 2025-10-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_paper_snippet_professor_affiliation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='authors',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='citation_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='journal',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='citations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='h_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='i10_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='profile_photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
