# Generated by Django 5.2.6 on 2025-10-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_paper_authors_paper_citation_count_paper_journal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='abstract',
            field=models.TextField(blank=True, null=True),
        ),
    ]
